### PR TITLE
Add LorElixir to README

### PR DESCRIPTION
**Pull request by petter-kaspersen**
Add my implementation of LoR Deck Codes written in Elixir. Currently supports encoding 100%.

### CODE REVIEW

**Comment by RiotTuxedo** [comment]
Looks like the library only supports decoding codes right now, correct?

**Comment by petter-kaspersen** [comment]
That's correct. Working on the encoding part of it. Should I wait until I support that before I submit a PR?

**Comment by RiotTuxedo** [comment]
Yes please. It's fine if you'd like to submit a library before it supports encoding and decoding, but we'll want to wait until the library supports both before we include it in the list of implementations.

**Comment by RiotTuxedo** [comment]
I've added your library to the list of implementations.

**Pull request closed without merging**
