### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by MarekSalgovic**
change version of Golang implementation:
- add bilgewater support

### CODE REVIEW

**Comment by RiotTuxedo** [comment]
It looks like there's no MAX_KNOWN_VERSION check in your library, correct? Just wanna make it wasn't accidentally overlooked.

**Comment by MarekSalgovic** [comment]
no it is not there, could you explain what it exactly is?

**Comment by RiotTuxedo** [comment]
The first couple bits of the encrypted deck code should indicate the version of the code that's being used and the library can determine if the code is a version it supports.
https://github.com/RiotGames/LoRDeckCodes/blob/master/LoRDeckCodes/LoRDeckEncoder.cs#L56

As an example, right now the MAX_KNOWN_VERSION = 2, because this version supports Bilgewater. If you use a new code in an older version of the library that only supports MAX_KNOWN_VERSION 1 then the library would tell you that the decode failed because it doesn't support the newer deck codes.

**Comment by MarekSalgovic** [comment]
thanks, i updated my lib (https://github.com/MarekSalgovic/lordeckoder/blob/e9c7d92392896ae8458a794884ec91c5e6ac07ca/decoder.go#L32)

thanks for clarifying, even though every deckcode with bilgewater cards i found still used 00010001 in header so i was not sure if the version check should be used in both decoding and encoding

**Comment by RiotTuxedo** [comment]
I actually noticed the same thing when I asked if you were checking the version in your lib 😄  I've escalated that the bilgewater cards are still returning version 1.

**Pull request merged**
