### PR TITLE
Fix sorting error in code

### PR DESCRIPTION
**Pull request by stelar7**
With the current test decks, the groups are not sorted based on card code.
Due to this, the 3 changed decks depended on encounter order to be equal.

This change forces the deck codes to be sorted so that 01DE019 is always before 01NX004 in cases where the outer lists have equal length.

### CODE REVIEW

**Comment by RiotTuxedo** [comment]
I'm not sure I fully understand the issue here. The deck code library [orders the card codes alphanumerically](https://github.com/RiotGames/LoRDeckCodes/blob/master/LoRDeckCodes/LoRDeckEncoder.cs#L187) after being put into groups, so the code should always be consistent regardless of the card order.

It looks like you changed the deck codes in the test data as well, as you saying these deck codes are invalid because the cards weren't properly sorted?

**Comment by stelar7** [comment]
The deck codes are valid, since technically the order of the cards does not matter.   
But since the code wants to ensure that every combination of the same cards end in the same code, its not valid.

As the comments say, it is supposed to sort `First by the number of set/faction combinations in each top-level list, Second by the alphanumeric order of the card codes within those lists.`

but what it really does it sort the outer list based on the length, then the inner lists based on alphanueric order.

Due to this, you can get a situation where you have an equal amout of cards in each top-level list, but due to encounter order, they are not sorted alphanumerically.

**Comment by RiotTuxedo** [comment]
Ah so if I understand you correctly, you're submitting a test case that will reveal the error in the way deck codes are generated, but not the fix itself?

**Comment by stelar7** [comment]
Yes.

**Comment by jeberemus** [comment]
Great catch @stelar7! Look good. On behalf of LoR folks, thanks for fixing!

**Pull request merged**
