### PR TITLE
Add ForDeckmacia to implementation list

### PR DESCRIPTION
**Pull request by Billzabob**

### CODE REVIEW

**Comment by Billzabob** [comment]
I see that some of these other libraries support a max version of 2 but I can't seem to find anywhere that talks about the difference between 1 and 2. Right now the README says:
> All encodings begin with 4 bits for format and 4 bits for version. Currently this is only 00010001.

If someone could point me to the difference I'd love to support the latest version as well.

**Comment by stelar7** [comment]
Version 2 has support for bilgewater cards

**Comment by Billzabob** [comment]
I added that info to the README, and updated my library to support Version 2.

**Comment by RiotTuxedo** [comment]
Thanks for suggesting the documentation on the versions and the addition of a Scala lib.

**Pull request merged**
