### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by stelar7**

### CODE REVIEW

**Comment by Billzabob** [comment]
Wouldn't adding support for version 3 before it's released break your encoder? It'll encode decks with 3 for the version which the game currently sees as invalid. I ask because I'm curious how I should handle this myself.

**Comment by RiotTuxedo** [comment]
@Billzabob yes it would, this is why we'll be merging our [PR](https://github.com/RiotGames/LoRDeckCodes/pull/57) on the day the expansion is released.

**Comment by Billzabob** [comment]
@RiotTuxedo Gotcha. I'll make a PR to add my own lib to the README then. I'll be updating it to version 3 on release day 👍

**Comment by Billzabob** [comment]
@RiotTuxedo Or should I just add it to this PR?

**Comment by RiotTuxedo** [comment]
Either or. I'll be going through the existing libraries day of and a couple days after to see which ones updated to version 3.

**Pull request merged**
